### PR TITLE
Converting to Maven project

### PR DESCRIPTION
**Pull request by Nunnery**
Project has been converted to a Maven project, Ant build is still intact.

### CODE REVIEW

**Comment by mharrah** [comment]
I see the Ant file is still there, but does it still work now that the code is moved? If the ant file is still there, it should work, and if we're not interested in maintaining backward compatibility with Ant we should just remove the build.xml file.

Also, I noticed a few minor code changes (removing periods, changing order of import statements), and changing a PMD rule config.  Intentional?

**Comment by frizbog** [comment]
I see the Ant file is still there, but does it still work now that the code is moved? If the ant file is still there, it should work, and if we're not interested in maintaining backward compatibility with Ant we should just remove the build.xml file.

Also, I noticed a few minor code changes (removing periods, changing order of import statements), and changing a PMD rule config.  Intentional?

**Comment by Nunnery** [comment]
The Ant file is still there and still works. Nothing was removed, so the Ant build should be unaffected other than having the change the source directories in it.

The code changes came from moving directories, I'll go back and fix that. The PMD rule config change was due to UseSingleton being deprecated in a more recent version of PMD. I was checking those docs and thus deprecated it. I can return it to its previous state.

**Comment by frizbog** [comment]
No need to change the UseSingleton rule...if PMD has deprecated it, I'm game...I never liked that rule very much anyway.

But yes, let's make sure the Ant build still works, or let's remove it.  Not good to have a build file in Git that doesn't work.

**Comment by Nunnery** [comment]
Corrected the Ant build script and reverted the accidental code change.

**Comment by Nunnery** [comment]
Ant build script tested and confirmed to be working after most recent commit 740f877a6fe59ea640923624b7ff7fb81f01136b.

**Pull request merged**
